name: LikeMindsFeed
options:
  bundleIdPrefix: com.sdk
  deploymentTarget:
    iOS: '13.0'
schemes:
  LikeMindsFeed:
    build:
      targets:
        LikeMindsFeed: all
targets:
  LikeMindsFeed:
    type: framework
    platform: iOS
    sources: 
      - LikeMindsFeed
    resources: 
      - LikeMindsFeed/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.Collabmates.LikeMindsFeed
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: 1.9.0
      CURRENT_PROJECT_VERSION: 12
      INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024 CollabMates Pvt. Ltd. All rights reserved."
