name: LikeMindsFeed
options:
  bundleIdPrefix: com.sdk
  deploymentTarget:
    iOS: '12.0'
schemes:
  LikeMindsFeed:
    build:
      targets:
        LikeMindsFeed: all
targets:
  LikeMindsFeed:
    type: framework
    platform: iOS
    sources: 
      - LikeMindsFeed
    resources: 
      - LikeMindsFeed/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sdk.LMFeed
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © $(CURRENT_YEAR) Your Company. All rights reserved."
